# GIT module saves username & password in .git, so using command module 

---
- hosts: myhosts
  vars_prompt: 
  - name: "githubuser" 
    prompt: "Enter your github username" 
    private: no 
  - name: "githubpassword" 
    prompt: "Enter your github password" 
    private: yes

  tasks:
  - name: Git clone
    expect:
      command: git clone https://github.com/myproject.git /home/madhudir
      responses:
        Username: "{{ githubuser }}" 
        Password: "{{ githubpassword }}" 
